### ISSUE TITLE
Please add a script for one-time subline merge

### ISSUE THREAD

**Issue by dabrahams** [paulaltin/git-subline-merge#2]
It's a fantastic tool, but I can't use it every time; it interferes with some other tools (I don't remember which—magit, maybe?).  I'd like to be able to invoke "git subline-merge ..." from the command-line, but the instructions make me change my config… which means that I use it less than I'd like.

Thanks!

**Comment by paulaltin** [comment]
Hi Dave, thanks for your message!

Do you mean that you want to invoke the script on a conflicted file after a merge or rebase has thrown an error, instead of during the operation? Perhaps with something like `git-subline-merge /path/to/file`? I think that should be doable.

I'd also be interested in trying to solve the issue you were having with magit, I'd love for this to work seamlessly with as many other git tools as possible. Is there any more information you could give me about how it was interfering with your other tools?

Thanks!

**Comment by paulaltin** [comment]
Note that this will still require a change to the default git config to enable diff3 merging, since without knowing the base version of a conflict the script can't resolve it.

**Comment by dabrahams** [comment]
> On Feb 5, 2019, at 3:14 PM, paulaltin <notifications@github.com> wrote:
> 
> Hi Dave, thanks for your message!
> 
> Do you mean that you want to invoke the script on a conflicted file after a merge or rebase has thrown an error, instead of during the operation? Perhaps with something like git-subline-merge /path/to/file? I think that should be doable.
> 
> 
Oh, that’s a *very* interesting idea, too, maybe even better than what I had in mind!

I was thinking it would be great to be able to invoke one thing instead of “git merge …” that would, effectively, modify $GIT_DIR/info/attributes, invoke "git merge…", and then restore  $GIT_DIR/info/attributes
> I'd also be interested in trying to solve the issue you were having with magit, I'd love for this to work seamlessly with as many other git tools as possible. Is there any more information you could give me about how it was interfering with your other tools?
> 

I’m afraid I don’t remember what the issue was; it was a while back.  I just came back to git-subline-merge because of a difficult merge I was having, but I haven’t run into issues yet.

**Comment by paulaltin** [comment]
Hi Dave,

OK, I see what you mean. I imagine it would be fairly easy to wrap this code up in a little script that modifies the config, runs the merge, and then resets everything to normal as you suggested. My only concern is that if the script were killed without the chance to restore everything, the git config may be left in a bad state.

In the meantime, I've pushed a change to the `manual` branch which should allow you to invoke the script manually on a single conflicted file. Could you maybe try it out and let me know if it's useful to you?

Thanks!

**Comment by dabrahams** [comment]
> On Feb 5, 2019, at 6:53 PM, paulaltin <notifications@github.com> wrote:
> 
> Hi Dave,
> 
> OK, I see what you mean. I imagine it would be fairly easy to wrap this code up in a little script that modifies the config, runs the merge, and then resets everything to normal as you suggested. My only concern is that if the script were killed without the chance to restore everything, the git config may be left in a bad state.
> 
> In the meantime, I've pushed a change to the manual branch which should allow you to invoke the script manually on a single conflicted file. Could you maybe try it out and let me know if it's useful to you?
> 
> 
Works a treat!

I love how much it resolves.  I still ran into cases where git thought I had “overlapping changes” and g-s-m couldn’t help me, but I think that’s a different problem than you’re trying to solve here.  OTOH, maybe g-s-m should become the One Solution To Rule Them All™ 😉

**Comment by paulaltin** [comment]
Great! I'll merge it in. Thanks for testing it, and thanks for the idea – I think it's made it much more useful :)

There are definitely still things that it can't resolve, and some times when it thinks the changes overlap but I disagree ;) If you do run across any conflicts that you think should be easily resolvable but fail, please feel free to make another issue and I'll have a look at them.

Thanks again!

**Comment by dabrahams** [comment]
> I’m afraid I don’t remember what the issue was; it was a while back.

Ah: it's rebase; #4
