### ISSUE TITLE
Document dependency on Gnu diff

### ISSUE THREAD

**Issue by dabrahams** [paulaltin/git-subline-merge#20]
The `--old-group-format` option used by `git-subline-merge` is not available in the BSD-based `diff` that comes with MacOS.  I installed `diffutils` with Homebrew to get around it.  Should be in the docs (or remove the dependency).

**Comment by paulaltin** [comment]
Related to #19, it seems that the version of `diff` bundled with macOS changed in Ventura.

**Comment by paulaltin** [comment]
Added in 38ced202.
