### ISSUE TITLE
Even in non-interactive mode, I'd like to inspect the results

### ISSUE THREAD

**Issue by dabrahams** [paulaltin/git-subline-merge#9]
It'd be useful if gsm would dump the result of its successful merges to stdout even in non-interactive mode, so I can go back and visually confirm that they're reasonable.

**Comment by paulaltin** [comment]
Hi @dabrahams, thanks for the suggestion!

Do you want it to always dump successful merges, or would you prefer having another environment variable switch to enable this behavior? I don't use non-interactive mode myself, so I'm not sure what the default should be..

**Comment by dabrahams** [comment]
We might need a switch eventually but I think it can start as unconditionally on. Thanks!!

**Comment by paulaltin** [comment]
OK, I've pushed a branch called 'print' which should have this behavior. Would you like to try it out and let me know if it works as you intended?

**Comment by dabrahams** [comment]
I finally got a chance to merge where GSL kicked in!  Can't really tell if it works, though, because I was in an emacs buffer and the control characters that are supposed to make the output colored got rendered literally:

```
[1m[92mgit-subline-merge resolved conflict 1 of 2 in Core/UnaryLayoutView.swift, resulting hunk was:[0m
[96m<<<<<<<[0m
            [layout, layoutContext, child] in

            return layout.sizeThatFits(
                in: proposedSize, context: layoutContext, child: child)
[96m>>>>>>>[0m
[1m[92mgit-subline-merge resolved conflict 2 of 2 in Core/UnaryLayoutView.swift, resulting hunk was:[0m
[96m<<<<<<<[0m
            [layout, layoutContext, child] in
            return layout.sizeThatFits(
                in: proposedSize, context: layoutContext, child: child)
[96m>>>>>>>[0m
[92m[1mResolved 2 of 2 conflicts in Core/UnaryLayoutView.swift[0m
```

**Comment by paulaltin** [comment]
Thanks for testing this @dabrahams.

I've opened a separate issue for the control character problem and pushed a potential fix to the same branch. It seems to work when I tried it from an emacs shell, but I may be using a different configuration to you. When you get a chance to test it, could you let me know how you go? Thanks!

**Comment by dabrahams** [comment]
I just had a chance to observe it in action, and it seems to work great!

**Comment by paulaltin** [comment]
OK, fantastic! I'll merge it in. Thanks for testing it, and for the suggestions :)

**Comment by dabrahams** [comment]
Report from the field: again, this is super-awesome.

**Comment by paulaltin** [comment]
Thanks! It's always great to hear that someone else finds this useful too :) And please let me know if you have any other issues or suggestions for improvement..
